name: Deploy Ingestion Service

on:
  push:
    branches: [ "main" ]
    # Only run if there is a merge on main from the gui-ingest path
    paths:
      - 'gui-ingestion/**'
      - '.github/workflows/deploy-ingestion.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Indispensable para que WIF genere el token temporal

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Autenticación con WIF 
      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Configurar Docker 
      - name: Authorize Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Construcción de la imagen 
      - name: Build and Push Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tesis-repo/ingestion-service:v1 \
            -f gui-ingestion/Dockerfile .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tesis-repo/ingestion-service:v1

      # Despliegue en Cloud Run 
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ingesta-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tesis-repo/ingestion-service:v1 \
            --region us-central1 \
            --set-env-vars ENV=CLOUD,BUCKET_NAME=sochoa-tesis-medical-data_from_nii \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL }}